### ISSUE TITLE
Removing dynamically created fields

### ISSUE THREAD

**Issue by timokleemann** [stevepolitodesign/rails-nested-form-example#6]
Hi Steve

Your code helped me a lot, so thanks a lot for that.

It seems it's not possible to remove dynamically created fields, though. 

To fix that I had to change your code to this:

```
class removeFields {
  ...
  iterateLinks() {
    if (this.links.length === 0) return;
    document.addEventListener('click', (e) => {
      if (e.target && e.target.className == 'remove_fields') {
        this.handleClick(e.target, e);
      }
    });
  }
  ...
}
```

I think if you update your code / tutorial it might help some of the folks out there. Because otherwise it's very very good and probably the best resource on adding nested fields with Rails and Javascript.

**Comment by stevepolitodesign** [comment]
Thanks for taking the time to diagnose and solve this issue. I went ahead and made these changes.

https://github.com/stevepolitodesign/rails-nested-form-example/blob/master/app/javascript/packs/nested-forms/removeFields.js
